env: "prod"
storage_path: "./storage/storage.db"

database_url: "postgres://postgres:ayatuly@localhost:5432/postgres"

http-server:
  address: "0.0.0.0:8010"
  timeout: 4s
  idle_timeout: 60s
  user: "samat"
