name: Deploy to Server

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Build Go application
      run: |
        cd short-url-b
        go mod download
        go build -o url-shortener cmd/main.go
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /path/to/your/backend
          git pull origin main
          go build -o url-shortener cmd/main.go
          sudo systemctl restart url-shortener
          sudo systemctl status url-shortener

  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: short-url-f/package-lock.json
    
    - name: Install dependencies
      run: |
        cd short-url-f
        npm ci
    
    - name: Build React app
      run: |
        cd short-url-f
        npm run build
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /path/to/your/frontend
          git pull origin main
          cd short-url-f
          npm ci
          npm run build
          sudo cp -r build/* /var/www/html/
          sudo systemctl reload nginx
